# Generated by Django 4.2.7 on 2023-12-09 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0002_bank_form'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bank_form',
            new_name='Customer',
        ),
    ]
