# Generated by Django 4.2.7 on 2023-12-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0004_material_customer_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='materials',
            field=models.ManyToManyField(to='bank_app.material'),
        ),
    ]
