# Generated by Django 4.2.7 on 2023-12-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0005_alter_customer_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='account_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
