# Generated by Django 4.2.7 on 2023-12-09 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0006_alter_customer_account_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='account_type',
        ),
    ]
