# Generated by Django 4.2.7 on 2023-12-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0008_remove_customer_materials_delete_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='materials',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
