# Generated by Django 4.2.7 on 2023-12-10 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0010_alter_customer_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='materials',
            field=models.CharField(max_length=100),
        ),
    ]
